package com.crafts.profileconsumer.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;
import java.util.Map;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "user_profile")
public class  UserProfileEO {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;
    @DynamoDBAttribute
    private String idempotencyKey;
    @DynamoDBAttribute
    private String companyName;

    @DynamoDBAttribute
    private String legalName;

    @DynamoDBAttribute
    private AddressEO businessAddress;

    @DynamoDBAttribute
    private AddressEO legalAddress;

    @DynamoDBAttribute
    private TaxIdentifiersEO taxIdentifiers;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String website;

    @DynamoDBAttribute
    private String consolidatedStatus;

    @DynamoDBAttribute
    private String consolidatedMessage;

    @DynamoDBAttribute
    private List<String> subscriptions;

    @DynamoDBAttribute
    private Map<String, ProductValidationStatusEO> subscriptionValidations;

    @DynamoDBAttribute
    private String timestamp;

}


